spring.application.name=btg
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/btg_fondos}
jwt.secret=${JWT_SECRET:dev-secret-key-just-for-local-testing-12345}
jwt.expirationMs=${JWT_EXPIRATION_MS:3600000}
logging.level.com.test.btg=INFO